### ISSUE TITLE
Mismatch between github and pypi versions

### ISSUE THREAD

**Issue by davide125** [jkwill87/teletype#4]
On this github repository, the latest tagged release is 1.3.2, but pypi has [1.33](https://pypi.org/project/teletype/1.3.3/) and [1.3.4](https://pypi.org/project/teletype/1.3.4/), which don't have corresponding tags in the repo, so it's hard to match them to the correct source.

**Comment by jkwill87** [comment]
The only changes between 1.3.3 .. 1.3.4 are type annotation fixes. I haven't cut a release for them but they have been included [as tags](https://github.com/jkwill87/teletype/tags). Happy to do so, however.
